import type { Track } from "./types/track.js";

/** Fixed 20s clips. `hit` uses a random start between 1:00–2:00 in the game. `script` (fan/AI) uses `SCRIPT_CLIP_START_MIN_SEC`–`SCRIPT_CLIP_START_MAX_SEC`; per-track `clipStartSec` is for typing / tooling only. */
export const CLIP_DURATION_SEC = 20;

/** Inclusive seconds: fake-AI (`script`) quiz clips start at a random offset in this window. */
export const SCRIPT_CLIP_START_MIN_SEC = 10;
export const SCRIPT_CLIP_START_MAX_SEC = 30;

const PLAYLIST_STORY =
  "Official-style Eurovision performance from a curated YouTube playlist (not fan/AI).";

const SCRIPT_NOTE =
  "AIROVISION / fan–AI Eurovision-style clip on YouTube — not an official Eurovision entry.";

export const TRACKS: Track[] = [
  {
    id: "neeli-floga",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=sSuE6rdOFB4",
    clipStartSec: 0,
    title: "FLÓGA",
    artist: "Nefeli with Friends",
    revealNote:
      "AIROVISION Edition 2 — Greece’s national-final style fan/A.I. showcase (not official Eurovision).",
  },
  {
    id: "sarah-fire-fantasy",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=gBx5lLrXg5I",
    clipStartSec: 0,
    title: "Fire & Fantasy",
    artist: "Sarah",
    revealNote:
      "AIROVISION 02 rehearsal-style fan content from Nicosia — not an official Eurovision entry.",
  },
  {
    id: "wales-down-the-pit",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=rwA20i38s7Q",
    clipStartSec: 0,
    title: "Down The Pit We Go",
    artist: "Jonesy & Evans",
    country: "Wales",
    revealNote:
      "AIROVISION Edition 2 — winner of Cymru Airovision (Wales national final). Community fan/AI showcase, not official Eurovision.",
  },
  {
    id: "italy-mamma-mia-fiore",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=VVU4dg4Fdf0",
    clipStartSec: 0,
    title: "Mamma Mia… Fiore – Canta",
    artist: "AIROVISION Italy (rehearsal)",
    country: "Italy",
    revealNote:
      "AIROVISION 02 — Semi-Final 1 first rehearsal from Nicosia. Fan/AI stage concept (@NordicVision), not official Eurovision.",
  },
  {
    id: "portugal-sf1-rehearsal",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=ccCPE9GuuSg",
    clipStartSec: 0,
    title: "Semi-Final 1 rehearsal",
    artist: "AIROVISION Portugal",
    country: "Portugal",
    revealNote:
      "AIROVISION 02 — Portugal Semi-Final 1 first rehearsal from Nicosia (~30s fan/AI clip). Not official Eurovision.",
  },
  {
    id: "yt-script-croatia-sf1",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Sphe0Sl2ic8",
    clipStartSec: 0,
    title: "AI Eurovision – Croatia | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    country: "Croatia",
    revealNote:
      "AIROVISION 02 — Croatia Semi-Final 1 rehearsal (Nicosia). Fan/AI showcase, not official Eurovision.",
  },

  {
    id: "yt-script-8Y_wnyD7CCQ",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=8Y_wnyD7CCQ",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Ireland 🇮🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-a_ziuJ7mQac",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=a_ziuJ7mQac",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – South Korea 🇰🇷 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-LlSCblqJzE0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=LlSCblqJzE0",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Switzerland 🇨🇭 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-booouE0PGtg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=booouE0PGtg",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Lithuania 🇱🇹 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-NPCYQFIozik",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=NPCYQFIozik",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  - Denmark 🇩🇰 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-UXfwv7iX-Z4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=UXfwv7iX-Z4",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇲🇦 Morocco | First Rehearsal | Semi-Final 1 | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-uVOA6pGs-8Y",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=uVOA6pGs-8Y",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇧🇪 Belgium | First Rehearsal | Semi-Final 1 | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vd8eE-iJB60",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vd8eE-iJB60",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  🇯🇵 Japan  · Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-Pd4nhBwWhWs",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Pd4nhBwWhWs",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇦🇱 Albania · Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-fO4Buvhj0d4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=fO4Buvhj0d4",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION Germany 🇩🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-LkffIuxk05E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=LkffIuxk05E",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  Estonia 🇪🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vI6j5Zdy5G4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vI6j5Zdy5G4",
    clipStartSec: 0,
    title: "🇨🇾 Amara – ANASA | AIROVISION Edition 2 — Cyprus’ National Final Winner 🌊✨",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-XsLa1bxCtSU",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=XsLa1bxCtSU",
    clipStartSec: 0,
    title: "🇯🇵 YUI NATSUKA – “QUIET STORM” | AIROVISION Edition 02 – Japan’s  Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-JAbzLrhISCg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=JAbzLrhISCg",
    clipStartSec: 0,
    title: "🏴󠁧󠁢󠁥󠁮󠁧󠁿MR PATALIEN – “I’M RIGHT HERE” | AIROVISION Edition 2 – England’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-UTgQrhK2g0E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=UTgQrhK2g0E",
    clipStartSec: 0,
    title: "🇪🇸 MALENA – “LLAMA” | AIROVISION Edition 02 – Spain’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-Ng0sgws1gfk",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Ng0sgws1gfk",
    clipStartSec: 0,
    title: "🇮🇸 ARNA LÍF – “VIÐ LIFUM” | Airovision Edition 02 – Iceland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-7IqmHFKXuEc",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=7IqmHFKXuEc",
    clipStartSec: 0,
    title: "🇵🇹 INÉA – “SOMA” | AIROVISION Edition 2 – Portugal’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-dDBliA-v0SA",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=dDBliA-v0SA",
    clipStartSec: 0,
    title: "🇲🇦 MARWA ARMANI – “FEEL THE FIRE” | AIROVISION Edition 2 – Morocco’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-ZqSW8II3YiY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=ZqSW8II3YiY",
    clipStartSec: 0,
    title: "🇧🇬 IVAN RADEV – “OBRATNO PRI TEB (BACK TO YOU)” | AIROVISION Edition 2 – Bulgaria’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-I1sBem900HI",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=I1sBem900HI",
    clipStartSec: 0,
    title: "🇳🇴 Mats Ulv – TACO FREDAG! | AIROVISION Edition 2 – Norway’s Official Entry 🌮🔥",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-17goaERbibY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=17goaERbibY",
    clipStartSec: 0,
    title: "🇸🇪 Sara Svensson – HELA SVERIGE | AIROVISION Edition 2 – Sweden’s Official Entry 🌾✨",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vdlq_uCl7_E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vdlq_uCl7_E",
    clipStartSec: 0,
    title: "🇱🇺 NALVINN – “THE THRONE IS EMPTY” | AIROVISION Edition 2 – Luxembourg’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-AgcpcA6Xm0g",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=AgcpcA6Xm0g",
    clipStartSec: 0,
    title: "🌍 mAIra – “TASTE THE WORLD” | AIROVISION Edition 2 – AIROPA’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-trrleNglPw0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=trrleNglPw0",
    clipStartSec: 0,
    title: "🇫🇮 SAUNABRO – “SAUNAKLONKKU” | AIROVISION Edition 2 – Finland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-QrQ0lahIUII",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=QrQ0lahIUII",
    clipStartSec: 0,
    title: "🇧🇪 CÉLUNE – “ÉCOUTE” | AIROVISION Edition 2 – Belgium’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-o8fIBg8m_I0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=o8fIBg8m_I0",
    clipStartSec: 0,
    title: "🇦🇱 MARITA – “EKLIPS” | AIROVISION Edition 2 – Albania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-BQqH-D2UzWo",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=BQqH-D2UzWo",
    clipStartSec: 0,
    title: "🇸🇲 Ninfa feat. U Striònu – “Sciò Sciò!” | AIROVISION Edition 2 – San Marino’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-8-k8BSR307w",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=8-k8BSR307w",
    clipStartSec: 0,
    title: "🇮🇪 Cian O’Sé – “Rising” | AIROVISION Edition 2 – Ireland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-nd5lMGHhbms",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=nd5lMGHhbms",
    clipStartSec: 0,
    title: "🇵🇱 “Crying in Polish” | AIROVISION Edition 2 – Poland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-6DCaggiM4zI",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=6DCaggiM4zI",
    clipStartSec: 0,
    title: "🇷🇸 Glarius – “GLAS” | AIROVISION Edition 2 – Serbia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-_CowqhwJt5s",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=_CowqhwJt5s",
    clipStartSec: 0,
    title: "🇲🇹 Alexandar – “Lightkeeper” | AIROVISION Edition 2 – Malta’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-HbtBGr_8MuY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=HbtBGr_8MuY",
    clipStartSec: 0,
    title: "🇩🇪 Mingo x Bubbu – “Greyhounds & Hearts” | AIROVISION Edition 2 – Germany’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-nYz3B7DbNDU",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=nYz3B7DbNDU",
    clipStartSec: 0,
    title: "🇷🇴 SARAH – “Fire & Fantasy” | AIROVISION Edition 2 – Romania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-3RzgrW4A6PQ",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=3RzgrW4A6PQ",
    clipStartSec: 0,
    title: "🇨🇭 VEREN – “Underwater Fire” | AIROVISION Edition 2 – Switzerland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-6P9XQIi3C9k",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=6P9XQIi3C9k",
    clipStartSec: 0,
    title: "🇭🇷 Lisa Genička ft MarkoX  - Break My Heart - AIROVISION Edition 2 - Croatias Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-bVYhSbSBx6Y",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=bVYhSbSBx6Y",
    clipStartSec: 0,
    title: "🇪🇬 NAWR – Nile & Neon - AIROVISION Edition 2 – Egypt’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-J1T4rnqXVwE",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=J1T4rnqXVwE",
    clipStartSec: 0,
    title: "🇦🇲 Emily James – “After Love” | AIROVISION Edition 2 – Armenia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-NslRi6oTfRk",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=NslRi6oTfRk",
    clipStartSec: 0,
    title: "🇨🇿 DaMa – “Dream of a Family” | AIROVISION Edition 2 – Czechia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-XhIQdkGFVRc",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=XhIQdkGFVRc",
    clipStartSec: 0,
    title: "🇱🇹 Luke Vilkas – Texts Never Sent (I Miss You) | AIROVISION Edition 2 – Lithuania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-1PePJJtMXDg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=1PePJJtMXDg",
    clipStartSec: 0,
    title: "🇩🇰 Freida Neilsinger – Breaking Through | AIROVISION Edition 2 – Denmark’s Entry",
    revealNote: SCRIPT_NOTE,
  },

  {
    id: "au-delta-eclipse",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=EUMCr1pnaMY",
    clipStartSec: 40,
    title: "Eclipse",
    artist: "Delta Goodrem",
    country: "Australia",
    year: 2026,
    story:
      "Delta Goodrem will represent Australia at the Eurovision Song Contest 2026 with the song “Eclipse”.",
  },
  {
    id: "cy-antigoni-jalla",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=TzSs51BiQrE",
    clipStartSec: 82,
    title: "JALLA",
    artist: "Antigoni",
    country: "Cyprus",
    year: 2026,
    story:
      "Antigoni will represent Cyprus at the Eurovision Song Contest 2026 with the song “JALLA”.",
  },
  {
    id: "yt-hit-xR4BFQYFzMU",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=xR4BFQYFzMU",
    clipStartSec: 0,
    title: "Friends - listen to your heartbeat - ESC Sweden 2001",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-_cYITo2AH0A",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=_cYITo2AH0A",
    clipStartSec: 0,
    title: "Eurovision 2001 21 Malta *Fabrizio Faniello* *Another Summer Night* 16:9 HQ",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-qNs-R9NU82I",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=qNs-R9NU82I",
    clipStartSec: 0,
    title: "Antique - (I Would) Die For You (E.S.C. 2001 BBC Broadcast)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-1TouzY3_yq0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=1TouzY3_yq0",
    clipStartSec: 0,
    title: "t.A.T.u. - Ne Ver Ne Boysia Ne Prosi (Russia - Final - Eurovision Song Contest 2003)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-eSkQmSug55g",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=eSkQmSug55g",
    clipStartSec: 0,
    title: "Six4One - If We All Give A Little (LIVE) | Switzerland 🇨🇭 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-kiORqJIala8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=kiORqJIala8",
    clipStartSec: 0,
    title: "Fabrizio Faniello - I Do (LIVE) | Malta 🇲🇹 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-7lvegAK4vOA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=7lvegAK4vOA",
    clipStartSec: 0,
    title: "Sidsel Ben Semmane - Twist Of Love (LIVE) | Denmark 🇩🇰 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-1SyPb8IOimE",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=1SyPb8IOimE",
    clipStartSec: 0,
    title: "Mihai Traistariu - Tornerò - 🇷🇴 Romania - Grand Final - Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-OYgE7O0OLyw",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=OYgE7O0OLyw",
    clipStartSec: 0,
    title: "Daz Sampson - Teenage Life (LIVE) | United Kingdom 🇬🇧 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-vFu5y0nP-RQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=vFu5y0nP-RQ",
    clipStartSec: 0,
    title: "Carola - Invincible (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-PxON-jTcBPA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=PxON-jTcBPA",
    clipStartSec: 0,
    title: "Dmitry Koldun - Work Your Magic (LIVE) | Belarus 🇧🇾 | Grand Final | Eurovision 2007",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-r02Lg8JIco0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=r02Lg8JIco0",
    clipStartSec: 0,
    title: "The Ark - The Worrying Kind (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2007",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-pSs1XHuFfuQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=pSs1XHuFfuQ",
    clipStartSec: 0,
    title: "Kenan Dogulu - Shake It Up Shekerim (Turkey) Live 2007 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-bridO-wD7c8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=bridO-wD7c8",
    clipStartSec: 0,
    title: "Sirusho - Qele, Qele (Armenia) Live 2008 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-kIRDbmpC2PI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=kIRDbmpC2PI",
    clipStartSec: 0,
    title: "Laka - Pokušaj (Bosnia & Herzegovina) Live 2008 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-x_iSoluR53U",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=x_iSoluR53U",
    clipStartSec: 0,
    title: "Charlotte Perrelli - Hero (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-L6M300uBc7U",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=L6M300uBc7U",
    clipStartSec: 0,
    title: "Ani Lorak - Shady Lady (LIVE) | Ukraine 🇺🇦 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-CZQjBCvFd9E",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=CZQjBCvFd9E",
    clipStartSec: 0,
    title: "Sébastien Tellier - Divine (LIVE) | France 🇫🇷 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-4HIk_7ZTBkM",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=4HIk_7ZTBkM",
    clipStartSec: 0,
    title: "Kalomira - Secret Combination - Greece 🇬🇷 - Grand Final - Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit--Nx6iVCaix0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=-Nx6iVCaix0",
    clipStartSec: 0,
    title: "Hadise - Düm Tek Tek (Turkey)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-C-VMHOlCyW8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=C-VMHOlCyW8",
    clipStartSec: 0,
    title: "Sunstroke Project & Olia Tira - Run Away (Moldova) Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-524Yy7JWBd4",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=524Yy7JWBd4",
    clipStartSec: 0,
    title: "maNga - We Could Be The Same - Turkey - Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-anVLKrv28hs",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=anVLKrv28hs",
    clipStartSec: 0,
    title: "\"France\" Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit--04pUETT7oI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=-04pUETT7oI",
    clipStartSec: 0,
    title: "Eric Saade - Popular (Sweden) - Live - 2011 Eurovision Song Contest Final",
    story: PLAYLIST_STORY,
  },
];
