import type { Track } from "./types/track.js";
import { TRACKS_FROM_YOUTUBE } from "./generated/tracksFromYoutube.js";
import { extractYoutubeVideoId } from "./youtube.js";

/** Fixed 20s clips. `hit` / `script` use random bands when length is known and >30s; ≤30s starts at 3s (clamped). Per-track `clipStartSec` is tooling / generator default. */
export const CLIP_DURATION_SEC = 20;

/** Inclusive seconds: fake-AI (`script`) quiz clips start at a random offset in this window. */
export const SCRIPT_CLIP_START_MIN_SEC = 10;
export const SCRIPT_CLIP_START_MAX_SEC = 30;

const PLAYLIST_STORY =
  "Official-style Eurovision performance from a curated YouTube playlist (not fan/AI).";

const SCRIPT_NOTE =
  "AIROVISION / fan–AI Eurovision-style clip on YouTube — not an official Eurovision entry.";

/**
 * Copies `youtubeDurationSec` from `TRACKS_FROM_YOUTUBE` (seconds from YouTube ISO duration, not ms).
 * Matches by `id` first, then by watch URL video id so hand-picked ids (e.g. `sarah-fire-fantasy`) still clamp to the same YouTube file as `yt-script-…`.
 */
function mergeYoutubeDurationsFromGenerated(base: Track[]): Track[] {
  const byId = new Map<string, number>();
  const byVideoId = new Map<string, number>();
  for (const t of TRACKS_FROM_YOUTUBE) {
    const d = t.youtubeDurationSec;
    if (d == null || !Number.isFinite(d) || d <= 0) continue;
    byId.set(t.id, d);
    const vid = extractYoutubeVideoId(t.youtubeUrl);
    if (!vid) continue;
    const prev = byVideoId.get(vid);
    if (prev === undefined || d > prev) {
      byVideoId.set(vid, d);
    }
  }
  return base.map((t) => {
    const fromId = byId.get(t.id);
    if (fromId !== undefined) return { ...t, youtubeDurationSec: fromId };
    const vid = extractYoutubeVideoId(t.youtubeUrl);
    const fromVid = vid ? byVideoId.get(vid) : undefined;
    if (fromVid !== undefined) return { ...t, youtubeDurationSec: fromVid };
    return t;
  });
}

const TRACKS_BASE: Track[] = [
  {
    id: "neeli-floga",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=sSuE6rdOFB4",
    clipStartSec: 0,
    title: "FLÓGA",
    artist: "Nefeli with Friends",
    revealNote:
      "AIROVISION Edition 2 — Greece’s national-final style fan/A.I. showcase (not official Eurovision).",
  },
  {
    id: "sarah-fire-fantasy",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=gBx5lLrXg5I",
    clipStartSec: 0,
    title: "Romania — Semi-Final 1 (first rehearsal)",
    artist: "AIROVISION 02",
    revealNote:
      "AIROVISION 02 rehearsal-style fan content from Nicosia — not an official Eurovision entry.",
  },
  {
    id: "wales-down-the-pit",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=rwA20i38s7Q",
    clipStartSec: 0,
    title: "Down The Pit We Go",
    artist: "Jonesy & Evans",
    country: "Wales",
    revealNote:
      "AIROVISION Edition 2 — winner of Cymru Airovision (Wales national final). Community fan/AI showcase, not official Eurovision.",
  },
  {
    id: "italy-mamma-mia-fiore",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=VVU4dg4Fdf0",
    clipStartSec: 0,
    title: "Mamma Mia… Fiore – Canta",
    artist: "AIROVISION Italy (rehearsal)",
    country: "Italy",
    revealNote:
      "AIROVISION 02 — Semi-Final 1 first rehearsal from Nicosia. Fan/AI stage concept (@NordicVision), not official Eurovision.",
  },
  {
    id: "portugal-sf1-rehearsal",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=ccCPE9GuuSg",
    clipStartSec: 0,
    title: "Semi-Final 1 rehearsal",
    artist: "AIROVISION Portugal",
    country: "Portugal",
    revealNote:
      "AIROVISION 02 — Portugal Semi-Final 1 first rehearsal from Nicosia (~30s fan/AI clip). Not official Eurovision.",
  },
  {
    id: "yt-script-croatia-sf1",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Sphe0Sl2ic8",
    clipStartSec: 0,
    title: "AI Eurovision – Croatia | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    country: "Croatia",
    revealNote:
      "AIROVISION 02 — Croatia Semi-Final 1 rehearsal (Nicosia). Fan/AI showcase, not official Eurovision.",
  },

  {
    id: "yt-script-8Y_wnyD7CCQ",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=8Y_wnyD7CCQ",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Ireland 🇮🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-a_ziuJ7mQac",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=a_ziuJ7mQac",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – South Korea 🇰🇷 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-LlSCblqJzE0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=LlSCblqJzE0",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Switzerland 🇨🇭 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-booouE0PGtg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=booouE0PGtg",
    clipStartSec: 0,
    title: "🤖🎵 AI Eurovision – Lithuania 🇱🇹 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-NPCYQFIozik",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=NPCYQFIozik",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  - Denmark 🇩🇰 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-UXfwv7iX-Z4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=UXfwv7iX-Z4",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇲🇦 Morocco | First Rehearsal | Semi-Final 1 | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-uVOA6pGs-8Y",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=uVOA6pGs-8Y",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇧🇪 Belgium | First Rehearsal | Semi-Final 1 | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vd8eE-iJB60",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vd8eE-iJB60",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  🇯🇵 Japan  · Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-Pd4nhBwWhWs",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Pd4nhBwWhWs",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION 🇦🇱 Albania · Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-fO4Buvhj0d4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=fO4Buvhj0d4",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION Germany 🇩🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-LkffIuxk05E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=LkffIuxk05E",
    clipStartSec: 0,
    title: "🤖🎶AI EUROVISION  Estonia 🇪🇪 | Semi-Final 1 – First Rehearsal | AIROVISION 02 (Nicosia)",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vI6j5Zdy5G4",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vI6j5Zdy5G4",
    clipStartSec: 0,
    title: "🇨🇾 Amara – ANASA | AIROVISION Edition 2 — Cyprus’ National Final Winner 🌊✨",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-XsLa1bxCtSU",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=XsLa1bxCtSU",
    clipStartSec: 0,
    title: "🇯🇵 YUI NATSUKA – “QUIET STORM” | AIROVISION Edition 02 – Japan’s  Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-JAbzLrhISCg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=JAbzLrhISCg",
    clipStartSec: 0,
    title: "🏴󠁧󠁢󠁥󠁮󠁧󠁿MR PATALIEN – “I’M RIGHT HERE” | AIROVISION Edition 2 – England’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-UTgQrhK2g0E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=UTgQrhK2g0E",
    clipStartSec: 0,
    title: "🇪🇸 MALENA – “LLAMA” | AIROVISION Edition 02 – Spain’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-Ng0sgws1gfk",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=Ng0sgws1gfk",
    clipStartSec: 0,
    title: "🇮🇸 ARNA LÍF – “VIÐ LIFUM” | Airovision Edition 02 – Iceland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-7IqmHFKXuEc",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=7IqmHFKXuEc",
    clipStartSec: 0,
    title: "🇵🇹 INÉA – “SOMA” | AIROVISION Edition 2 – Portugal’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-dDBliA-v0SA",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=dDBliA-v0SA",
    clipStartSec: 0,
    title: "🇲🇦 MARWA ARMANI – “FEEL THE FIRE” | AIROVISION Edition 2 – Morocco’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-ZqSW8II3YiY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=ZqSW8II3YiY",
    clipStartSec: 0,
    title: "🇧🇬 IVAN RADEV – “OBRATNO PRI TEB (BACK TO YOU)” | AIROVISION Edition 2 – Bulgaria’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-I1sBem900HI",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=I1sBem900HI",
    clipStartSec: 0,
    title: "🇳🇴 Mats Ulv – TACO FREDAG! | AIROVISION Edition 2 – Norway’s Official Entry 🌮🔥",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-17goaERbibY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=17goaERbibY",
    clipStartSec: 0,
    title: "🇸🇪 Sara Svensson – HELA SVERIGE | AIROVISION Edition 2 – Sweden’s Official Entry 🌾✨",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-vdlq_uCl7_E",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=vdlq_uCl7_E",
    clipStartSec: 0,
    title: "🇱🇺 NALVINN – “THE THRONE IS EMPTY” | AIROVISION Edition 2 – Luxembourg’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-AgcpcA6Xm0g",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=AgcpcA6Xm0g",
    clipStartSec: 0,
    title: "🌍 mAIra – “TASTE THE WORLD” | AIROVISION Edition 2 – AIROPA’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-trrleNglPw0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=trrleNglPw0",
    clipStartSec: 0,
    title: "🇫🇮 SAUNABRO – “SAUNAKLONKKU” | AIROVISION Edition 2 – Finland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-QrQ0lahIUII",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=QrQ0lahIUII",
    clipStartSec: 0,
    title: "🇧🇪 CÉLUNE – “ÉCOUTE” | AIROVISION Edition 2 – Belgium’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-o8fIBg8m_I0",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=o8fIBg8m_I0",
    clipStartSec: 0,
    title: "🇦🇱 MARITA – “EKLIPS” | AIROVISION Edition 2 – Albania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-BQqH-D2UzWo",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=BQqH-D2UzWo",
    clipStartSec: 0,
    title: "🇸🇲 Ninfa feat. U Striònu – “Sciò Sciò!” | AIROVISION Edition 2 – San Marino’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-8-k8BSR307w",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=8-k8BSR307w",
    clipStartSec: 0,
    title: "🇮🇪 Cian O’Sé – “Rising” | AIROVISION Edition 2 – Ireland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-nd5lMGHhbms",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=nd5lMGHhbms",
    clipStartSec: 0,
    title: "🇵🇱 “Crying in Polish” | AIROVISION Edition 2 – Poland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-6DCaggiM4zI",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=6DCaggiM4zI",
    clipStartSec: 0,
    title: "🇷🇸 Glarius – “GLAS” | AIROVISION Edition 2 – Serbia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-_CowqhwJt5s",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=_CowqhwJt5s",
    clipStartSec: 0,
    title: "🇲🇹 Alexandar – “Lightkeeper” | AIROVISION Edition 2 – Malta’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-HbtBGr_8MuY",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=HbtBGr_8MuY",
    clipStartSec: 0,
    title: "🇩🇪 Mingo x Bubbu – “Greyhounds & Hearts” | AIROVISION Edition 2 – Germany’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-nYz3B7DbNDU",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=nYz3B7DbNDU",
    clipStartSec: 0,
    title: "🇷🇴 SARAH – “Fire & Fantasy” | AIROVISION Edition 2 – Romania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-3RzgrW4A6PQ",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=3RzgrW4A6PQ",
    clipStartSec: 0,
    title: "🇨🇭 VEREN – “Underwater Fire” | AIROVISION Edition 2 – Switzerland’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-6P9XQIi3C9k",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=6P9XQIi3C9k",
    clipStartSec: 0,
    title: "🇭🇷 Lisa Genička ft MarkoX  - Break My Heart - AIROVISION Edition 2 - Croatias Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-bVYhSbSBx6Y",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=bVYhSbSBx6Y",
    clipStartSec: 0,
    title: "🇪🇬 NAWR – Nile & Neon - AIROVISION Edition 2 – Egypt’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-J1T4rnqXVwE",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=J1T4rnqXVwE",
    clipStartSec: 0,
    title: "🇦🇲 Emily James – “After Love” | AIROVISION Edition 2 – Armenia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-NslRi6oTfRk",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=NslRi6oTfRk",
    clipStartSec: 0,
    title: "🇨🇿 DaMa – “Dream of a Family” | AIROVISION Edition 2 – Czechia’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-XhIQdkGFVRc",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=XhIQdkGFVRc",
    clipStartSec: 0,
    title: "🇱🇹 Luke Vilkas – Texts Never Sent (I Miss You) | AIROVISION Edition 2 – Lithuania’s Entry",
    revealNote: SCRIPT_NOTE,
  },
  {
    id: "yt-script-1PePJJtMXDg",
    kind: "script",
    youtubeUrl: "https://www.youtube.com/watch?v=1PePJJtMXDg",
    clipStartSec: 0,
    title: "🇩🇰 Freida Neilsinger – Breaking Through | AIROVISION Edition 2 – Denmark’s Entry",
    revealNote: SCRIPT_NOTE,
  },

  {
    id: "yt-hit-xWCnWSoG8nI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=xWCnWSoG8nI",
    clipStartSec: 0,
    title: "Noam Bettan - Michelle | Israel 🇮🇱 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-EUMCr1pnaMY",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=EUMCr1pnaMY",
    clipStartSec: 0,
    title: "Delta Goodrem - Eclipse | Australia 🇦🇺 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-xKzEP9dwoss",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=xKzEP9dwoss",
    clipStartSec: 0,
    title: "Søren Torpegaard Lund - Før Vi Går Hjem | Denmark 🇩🇰 | National Final Performance | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-NGwNTd_DA9s",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=NGwNTd_DA9s",
    clipStartSec: 0,
    title: "Akylas - Ferto | Greece 🇬🇷 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-coh-lygCINY",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=coh-lygCINY",
    clipStartSec: 0,
    title: "Bzikebi - On Replay | Georgia 🇬🇪 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-yn0YmI0dPb8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=yn0YmI0dPb8",
    clipStartSec: 0,
    title: "Alexandra Căpitănescu - Choke Me | Romania 🇷🇴 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-TzSs51BiQrE",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=TzSs51BiQrE",
    clipStartSec: 0,
    title: "Antigoni - JALLA | Cyprus 🇨🇾 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-ujoCYrvvTYQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=ujoCYrvvTYQ",
    clipStartSec: 0,
    title: "Monroe - Regarde ! | France 🇫🇷 | Official Music Video #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-9sfI4g6DWTU",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=9sfI4g6DWTU",
    clipStartSec: 0,
    title: "ESSYLA - Dancing on the Ice | Belgium 🇧🇪 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-nuvy2d60HbI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=nuvy2d60HbI",
    clipStartSec: 0,
    title: "Tamara Živković - Nova Zora | Montenegro 🇲🇪 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-AzvRc3eH_rA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=AzvRc3eH_rA",
    clipStartSec: 0,
    title: "Sarah Engels - Fire | Germany 🇩🇪 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-6ea25aRGpLo",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=6ea25aRGpLo",
    clipStartSec: 0,
    title: "Daniel Zizka - CROSSROADS | Czechia 🇨🇿 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-J3oGYo_mekw",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=J3oGYo_mekw",
    clipStartSec: 0,
    title: "DARA - Bangaranga | Bulgaria 🇧🇬 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-9bfwNIYb96Q",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=9bfwNIYb96Q",
    clipStartSec: 0,
    title: "Linda Lampenius x Pete Parkkonen - Liekinheitin  | Finland 🇫🇮 | Official Music Video | #Eurovision",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-V406FAGkhyQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=V406FAGkhyQ",
    clipStartSec: 0,
    title: "Sal Da Vinci - Per Sempre Sì | Italy 🇮🇹 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-hQt-ZCGVVW4",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=hQt-ZCGVVW4",
    clipStartSec: 0,
    title: "FELICIA - My System (Official Performance Video)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-wOQe-fQSFxg",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=wOQe-fQSFxg",
    clipStartSec: 0,
    title: "SENHIT - Superstar | San Marino 🇸🇲 | National Final Performance | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-PfpYGAzW5dM",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=PfpYGAzW5dM",
    clipStartSec: 0,
    title: "Veronica Fusaro - Alice | Switzerland 🇨🇭 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-8Brb0M3UgEA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=8Brb0M3UgEA",
    clipStartSec: 0,
    title: "Vanilla Ninja - Too Epic To Be True (ESC Version) | Official Music Video",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-CW6mQLBh6Js",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=CW6mQLBh6Js",
    clipStartSec: 0,
    title: "AIDAN - Bella | Malta 🇲🇹 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-5EXoK-lgocw",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=5EXoK-lgocw",
    clipStartSec: 0,
    title: "SIMÓN - Paloma Rumba | Armenia 🇦🇲 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-q78cnYIoF9Y",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=q78cnYIoF9Y",
    clipStartSec: 0,
    title: "ALICJA - Pray | Poland 🇵🇱 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-b9AdRrA554o",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=b9AdRrA554o",
    clipStartSec: 0,
    title: "Alis - Nân | Albania 🇦🇱 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-SoEXezpblAc",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=SoEXezpblAc",
    clipStartSec: 0,
    title: "LELÉKA - Ridnym | Ukraine 🇺🇦 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-niMKvJ-Itq8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=niMKvJ-Itq8",
    clipStartSec: 0,
    title: "LOOK MUM NO COMPUTER - Eins, Zwei, Drei | United Kingdom 🇬🇧 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-DmVfJSRqgnI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=DmVfJSRqgnI",
    clipStartSec: 0,
    title: "Eva Marija - Mother Nature | Luxembourg 🇱🇺 | National Final Performance | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-yeYEYUHDgyc",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=yeYEYUHDgyc",
    clipStartSec: 0,
    title: "Lion Ceccah - Sólo Quiero Más (Eurovision Version)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-vl7Jqnw10sU",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=vl7Jqnw10sU",
    clipStartSec: 0,
    title: "LELEK - Andromeda | Croatia 🇭🇷 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-FJTLKBOOE98",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=FJTLKBOOE98",
    clipStartSec: 0,
    title: "LAVINA - Kraj Mene | Serbia 🇷🇸 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-6C2ivaB5D00",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=6C2ivaB5D00",
    clipStartSec: 0,
    title: "Atvara - Ēnā | Latvia 🇱🇻 | National Final Performance #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-jyHaE6GqaaQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=jyHaE6GqaaQ",
    clipStartSec: 0,
    title: "Bandidos do Cante - Rosa | Portugal 🇵🇹 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-zPGP9ZphxiY",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=zPGP9ZphxiY",
    clipStartSec: 0,
    title: "COSMÓ - Tanzschein | Austria 🇦🇹 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-iMDBPe25JhM",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=iMDBPe25JhM",
    clipStartSec: 0,
    title: "JIVA - Just Go | Azerbaijan 🇦🇿 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-MasllzWk_bQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=MasllzWk_bQ",
    clipStartSec: 0,
    title: "JONAS LOVV - YA YA YA | Norway 🇳🇴 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-SViojHjNSzc",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=SViojHjNSzc",
    clipStartSec: 0,
    title: "Satoshi - Viva, Moldova!  | Moldova 🇲🇩 | Official Music Video | #Eurovision2026",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-xR4BFQYFzMU",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=xR4BFQYFzMU",
    clipStartSec: 0,
    title: "Friends - listen to your heartbeat - ESC Sweden 2001",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-_cYITo2AH0A",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=_cYITo2AH0A",
    clipStartSec: 0,
    title: "Eurovision 2001 21 Malta *Fabrizio Faniello* *Another Summer Night* 16:9 HQ",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-qNs-R9NU82I",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=qNs-R9NU82I",
    clipStartSec: 0,
    title: "Antique - (I Would) Die For You (E.S.C. 2001 BBC Broadcast)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-1TouzY3_yq0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=1TouzY3_yq0",
    clipStartSec: 0,
    title: "t.A.T.u. - Ne Ver Ne Boysia Ne Prosi (Russia - Final - Eurovision Song Contest 2003)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-eSkQmSug55g",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=eSkQmSug55g",
    clipStartSec: 0,
    title: "Six4One - If We All Give A Little (LIVE) | Switzerland 🇨🇭 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-kiORqJIala8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=kiORqJIala8",
    clipStartSec: 0,
    title: "Fabrizio Faniello - I Do (LIVE) | Malta 🇲🇹 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-7lvegAK4vOA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=7lvegAK4vOA",
    clipStartSec: 0,
    title: "Sidsel Ben Semmane - Twist Of Love (LIVE) | Denmark 🇩🇰 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-1SyPb8IOimE",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=1SyPb8IOimE",
    clipStartSec: 0,
    title: "Mihai Traistariu - Tornerò - 🇷🇴 Romania - Grand Final - Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-OYgE7O0OLyw",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=OYgE7O0OLyw",
    clipStartSec: 0,
    title: "Daz Sampson - Teenage Life (LIVE) | United Kingdom 🇬🇧 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-vFu5y0nP-RQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=vFu5y0nP-RQ",
    clipStartSec: 0,
    title: "Carola - Invincible (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2006",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-PxON-jTcBPA",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=PxON-jTcBPA",
    clipStartSec: 0,
    title: "Dmitry Koldun - Work Your Magic (LIVE) | Belarus 🇧🇾 | Grand Final | Eurovision 2007",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-r02Lg8JIco0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=r02Lg8JIco0",
    clipStartSec: 0,
    title: "The Ark - The Worrying Kind (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2007",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-pSs1XHuFfuQ",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=pSs1XHuFfuQ",
    clipStartSec: 0,
    title: "Kenan Dogulu - Shake It Up Shekerim (Turkey) Live 2007 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-bridO-wD7c8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=bridO-wD7c8",
    clipStartSec: 0,
    title: "Sirusho - Qele, Qele (Armenia) Live 2008 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-kIRDbmpC2PI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=kIRDbmpC2PI",
    clipStartSec: 0,
    title: "Laka - Pokušaj (Bosnia & Herzegovina) Live 2008 Eurovision Song Contest",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-x_iSoluR53U",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=x_iSoluR53U",
    clipStartSec: 0,
    title: "Charlotte Perrelli - Hero (LIVE) | Sweden 🇸🇪 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-L6M300uBc7U",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=L6M300uBc7U",
    clipStartSec: 0,
    title: "Ani Lorak - Shady Lady (LIVE) | Ukraine 🇺🇦 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-CZQjBCvFd9E",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=CZQjBCvFd9E",
    clipStartSec: 0,
    title: "Sébastien Tellier - Divine (LIVE) | France 🇫🇷 | Grand Final | Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-4HIk_7ZTBkM",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=4HIk_7ZTBkM",
    clipStartSec: 0,
    title: "Kalomira - Secret Combination - Greece 🇬🇷 - Grand Final - Eurovision 2008",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit--Nx6iVCaix0",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=-Nx6iVCaix0",
    clipStartSec: 0,
    title: "Hadise - Düm Tek Tek (Turkey)",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-C-VMHOlCyW8",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=C-VMHOlCyW8",
    clipStartSec: 0,
    title: "Sunstroke Project & Olia Tira - Run Away (Moldova) Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-524Yy7JWBd4",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=524Yy7JWBd4",
    clipStartSec: 0,
    title: "maNga - We Could Be The Same - Turkey - Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit-anVLKrv28hs",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=anVLKrv28hs",
    clipStartSec: 0,
    title: "\"France\" Eurovision Song Contest 2010",
    story: PLAYLIST_STORY,
  },
  {
    id: "yt-hit--04pUETT7oI",
    kind: "hit",
    youtubeUrl: "https://www.youtube.com/watch?v=-04pUETT7oI",
    clipStartSec: 0,
    title: "Eric Saade - Popular (Sweden) - Live - 2011 Eurovision Song Contest Final",
    story: PLAYLIST_STORY,
  },
];

export const TRACKS: Track[] = mergeYoutubeDurationsFromGenerated(TRACKS_BASE);
